ALTER TABLE Teams 
	ADD CONSTRAINT foreignTeams FOREIGN KEY (coachID)
	REFERENCES Persons(personID)
	ON DELETE SET DEFAULT
	ON UPDATE SET DEFAULT;

ALTER TABLE GamePlayers
	ADD CONSTRAINT foreignGamePlayers FOREIGN KEY (gameID)
	REFERENCES Games(gameID)
	ON UPDATE CASCADE
	ON DELETE SET DEFAULT;

ALTER TABLE GamePLayers
	ADD CONSTRAINT foreignPlayers FOREIGN KEY (playerID)
	REFERENCES Players(playerID)
	ON UPDATE CASCADE
	ON DELETE CASCADE;
